./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=Yes RoommateHasFlu=Yes
# ./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=No CoworkerHasFlu=Yes,RoommateHasFlu=Yes,MaryIsVaccinated=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=Yes CoworkerHasFlu=Yes,RoommateHasFlu=Yes,MaryIsVaccinated=No
# ./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=No CoworkerHasFlu=Yes,RoommateHasFlu=Yes,MaryIsVaccinated=No 
# ./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=Yes CoworkerHasFlu=Yes,RoommateHasFlu=No,MaryIsVaccinated=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=No CoworkerHasFlu=Yes,RoommateHasFlu=No,MaryIsVaccinated=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=Yes CoworkerHasFlu=Yes,RoommateHasFlu=No,MaryIsVaccinated=No 
# ./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=No CoworkerHasFlu=Yes,RoommateHasFlu=No,MaryIsVaccinated=No 
# ./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=Yes CoworkerHasFlu=No,RoommateHasFlu=Yes,MaryIsVaccinated=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=No CoworkerHasFlu=No,RoommateHasFlu=Yes,MaryIsVaccinated=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=Yes CoworkerHasFlu=No,RoommateHasFlu=Yes,MaryIsVaccinated=No 
# ./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=No CoworkerHasFlu=No,RoommateHasFlu=Yes,MaryIsVaccinated=No 
# ./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=Yes CoworkerHasFlu=No,RoommateHasFlu=No,MaryIsVaccinated=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=No CoworkerHasFlu=No,RoommateHasFlu=No,MaryIsVaccinated=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=Yes CoworkerHasFlu=No,RoommateHasFlu=No,MaryIsVaccinated=No 
# ./bayes-query network-extended.txt cpd-extended.txt MaryGetsFlu=No CoworkerHasFlu=No,RoommateHasFlu=No,MaryIsVaccinated=No 
# ./bayes-query network-extended.txt cpd-extended.txt RoommateHasFlu=Yes FluRate=Mild 
# ./bayes-query network-extended.txt cpd-extended.txt RoommateHasFlu=No FluRate=Mild 
# ./bayes-query network-extended.txt cpd-extended.txt RoommateHasFlu=Yes FluRate=Moderate 
# ./bayes-query network-extended.txt cpd-extended.txt RoommateHasFlu=No FluRate=Moderate 
# ./bayes-query network-extended.txt cpd-extended.txt RoommateHasFlu=Yes FluRate=Severe 
# ./bayes-query network-extended.txt cpd-extended.txt RoommateHasFlu=No FluRate=Severe 
# ./bayes-query network-extended.txt cpd-extended.txt CoworkerHasFlu=Yes FluRate=Mild 
# ./bayes-query network-extended.txt cpd-extended.txt CoworkerHasFlu=No FluRate=Mild 
# ./bayes-query network-extended.txt cpd-extended.txt CoworkerHasFlu=Yes FluRate=Moderate 
# ./bayes-query network-extended.txt cpd-extended.txt CoworkerHasFlu=No FluRate=Moderate 
# ./bayes-query network-extended.txt cpd-extended.txt CoworkerHasFlu=Yes FluRate=Severe 
# ./bayes-query network-extended.txt cpd-extended.txt CoworkerHasFlu=No FluRate=Severe 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Mild PreviousFluRate=Mild,IsFluSeason=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Moderate PreviousFluRate=Mild,IsFluSeason=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Severe PreviousFluRate=Mild,IsFluSeason=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Mild PreviousFluRate=Moderate,IsFluSeason=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Moderate PreviousFluRate=Moderate,IsFluSeason=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Severe PreviousFluRate=Moderate,IsFluSeason=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Mild PreviousFluRate=Severe,IsFluSeason=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Moderate PreviousFluRate=Severe,IsFluSeason=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Severe PreviousFluRate=Severe,IsFluSeason=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Mild PreviousFluRate=Mild,IsFluSeason=No 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Moderate PreviousFluRate=Mild,IsFluSeason=No 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Severe PreviousFluRate=Mild,IsFluSeason=No 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Mild PreviousFluRate=Moderate,IsFluSeason=No 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Moderate PreviousFluRate=Moderate,IsFluSeason=No 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Severe PreviousFluRate=Moderate,IsFluSeason=No 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Mild PreviousFluRate=Severe,IsFluSeason=No 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Moderate PreviousFluRate=Severe,IsFluSeason=No 
# ./bayes-query network-extended.txt cpd-extended.txt FluRate=Severe PreviousFluRate=Severe,IsFluSeason=No 
# ./bayes-query network-extended.txt cpd-extended.txt PreviousFluRate=Mild IsFluSeason=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt PreviousFluRate=Moderate IsFluSeason=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt PreviousFluRate=Severe IsFluSeason=Yes 
# ./bayes-query network-extended.txt cpd-extended.txt PreviousFluRate=Mild IsFluSeason=No 
# ./bayes-query network-extended.txt cpd-extended.txt PreviousFluRate=Moderate IsFluSeason=No 
# ./bayes-query network-extended.txt cpd-extended.txt PreviousFluRate=Severe IsFluSeason=No 

